"""Streamlit UI for ecoRTA M1-M2-M3 workflow.

This UI is intentionally thin:
- Collects user inputs.
- Executes the existing full workflow CLI.
- Displays generated CSV/JSON/PNG artifacts.
- Visualizes M1 well/history data, M2 PVT data, and M3 DCA outputs.
- Allows interactive DCA fit-window selection from production history.

No PVT, well-integration, or DCA calculation logic is duplicated here.
"""

from __future__ import annotations

import json
import subprocess
import sys
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any

import pandas as pd
import streamlit as st

try:
    import plotly.graph_objects as go
except ImportError:  # pragma: no cover
    go = None


PROJECT_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_DIR = PROJECT_ROOT / "output"
UI_INPUT_DIR = PROJECT_ROOT / "data" / "ui_uploads"

FORECAST_START_RATE_MODES = (
    "fitted",
    "last-window-rate",
    "manual",
)

M1_RATE_COLUMNS = ("qo_stb_d", "qg_mscf_d", "qw_stb_d")
M1_PRESSURE_COLUMNS = (
    "whp_psia",
    "pwf_used_psia",
    "pwf_measured_psia",
    "pwf_estimated_psia",
)
M2_PVT_COLUMNS = (
    "bo",
    "rs",
    "mu_o_cp",
    "rho_o_lbft3",
    "pb_psia",
)

SESSION_USE_FIT_FROM = "use_fit_from_date"
SESSION_USE_FIT_TO = "use_fit_to_date"
SESSION_FIT_FROM_DATE = "fit_from_date_value"
SESSION_FIT_TO_DATE = "fit_to_date_value"
SESSION_PENDING_FIT_WINDOW = "pending_fit_window_selection"


@dataclass(frozen=True)
class WorkflowArtifacts:
    """Expected output artifacts generated by the full workflow."""

    enriched_history_csv: Path
    dca_fit_results_csv: Path
    dca_qc_report_json: Path
    dca_rate_fit_png: Path
    dca_forecast_plot_png: Path

    @classmethod
    def for_well(cls, well_id: str) -> "WorkflowArtifacts":
        safe_well_id = well_id.strip()
        return cls(
            enriched_history_csv=OUTPUT_DIR / f"{safe_well_id}_history_enriched.csv",
            dca_fit_results_csv=OUTPUT_DIR / f"{safe_well_id}_dca_fit_results.csv",
            dca_qc_report_json=OUTPUT_DIR / f"{safe_well_id}_dca_qc_report.json",
            dca_rate_fit_png=OUTPUT_DIR / f"{safe_well_id}_dca_rate_fit.png",
            dca_forecast_plot_png=OUTPUT_DIR / f"{safe_well_id}_dca_forecast_plot.png",
        )


def configure_page() -> None:
    """Configure Streamlit page defaults."""
    st.set_page_config(
        page_title="ecoRTA | M1-M2-M3",
        page_icon="📉",
        layout="wide",
    )


def ensure_dirs() -> None:
    """Create runtime folders if they do not exist."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    UI_INPUT_DIR.mkdir(parents=True, exist_ok=True)


def initialize_session_defaults() -> None:
    """Initialize Streamlit session state for DCA controls.

    Pending fit-window selections are applied here before sidebar widgets
    are instantiated. Streamlit does not allow modifying widget-backed keys
    after the widget has already been created in the same run.
    """
    pending_window = st.session_state.pop(SESSION_PENDING_FIT_WINDOW, None)

    if pending_window is not None:
        try:
            start_date = date.fromisoformat(pending_window["start_date"])
            end_date = date.fromisoformat(pending_window["end_date"])

            st.session_state[SESSION_USE_FIT_FROM] = True
            st.session_state[SESSION_USE_FIT_TO] = True
            st.session_state[SESSION_FIT_FROM_DATE] = start_date
            st.session_state[SESSION_FIT_TO_DATE] = end_date
        except (KeyError, TypeError, ValueError):
            pass

    st.session_state.setdefault(SESSION_USE_FIT_FROM, True)
    st.session_state.setdefault(SESSION_USE_FIT_TO, True)
    st.session_state.setdefault(SESSION_FIT_FROM_DATE, date(2024, 7, 1))
    st.session_state.setdefault(SESSION_FIT_TO_DATE, date(2025, 11, 30))


def apply_light_css() -> None:
    """Apply small UI polish."""
    st.markdown(
        """
        <style>
        div.stButton > button:first-child {
            border-radius: 0.55rem;
            font-weight: 600;
        }

        div[data-testid="stMetric"] {
            background-color: #f8fafc;
            border: 1px solid #e5e7eb;
            padding: 0.75rem;
            border-radius: 0.75rem;
        }

        .small-muted {
            color: #6b7280;
            font-size: 0.9rem;
        }
        </style>
        """,
        unsafe_allow_html=True,
    )


def save_uploaded_file(uploaded_file: Any, target_name: str) -> Path | None:
    """Persist an uploaded Streamlit file and return its local path."""
    if uploaded_file is None:
        return None

    target_path = UI_INPUT_DIR / target_name
    target_path.write_bytes(uploaded_file.getbuffer())
    return target_path


def read_json(path: Path) -> dict[str, Any]:
    """Read a JSON object from disk."""
    with path.open("r", encoding="utf-8") as file:
        data = json.load(file)

    if not isinstance(data, dict):
        msg = f"El archivo JSON no contiene un objeto raíz válido: {path}"
        raise ValueError(msg)

    return data


def read_csv_safe(path: Path) -> pd.DataFrame | None:
    """Read CSV safely and normalize date column when available."""
    if not path.exists():
        return None

    try:
        df = pd.read_csv(path)
    except Exception as exc:  # noqa: BLE001
        st.error(f"No fue posible leer `{path.name}`: {exc}")
        return None

    if "date" in df.columns:
        df["date"] = pd.to_datetime(df["date"], errors="coerce")
        df = df.sort_values("date")

    return df


def as_float(value: Any, default: float = 0.0) -> float:
    """Convert a value to float safely."""
    try:
        if value is None:
            return default
        return float(value)
    except (TypeError, ValueError):
        return default


def existing_columns(df: pd.DataFrame, columns: tuple[str, ...]) -> list[str]:
    """Return columns that exist in a dataframe."""
    return [column for column in columns if column in df.columns]


def build_full_workflow_command(
    *,
    well_id: str,
    fit_from_date: date | None,
    fit_to_date: date | None,
    exclude_first_n: int,
    forecast_days: int,
    abandonment_rate: float,
    forecast_start_rate_mode: str,
    forecast_start_rate: float | None,
    history_csv: Path | None,
    pvt_config_json: Path | None,
) -> list[str]:
    """Build the existing CLI command for the full M1-M2-M3 workflow."""
    if forecast_start_rate_mode not in FORECAST_START_RATE_MODES:
        msg = f"Modo de tasa inicial de forecast no soportado: {forecast_start_rate_mode}"
        raise ValueError(msg)

    cmd = [
        sys.executable,
        "-m",
        "src.pipeline.run_full_workflow",
        "--well-id",
        well_id,
        "--exclude-first-n",
        str(exclude_first_n),
        "--forecast-days",
        str(forecast_days),
        "--abandonment-rate",
        str(abandonment_rate),
        "--forecast-start-rate-mode",
        forecast_start_rate_mode,
    ]

    if fit_from_date is not None:
        cmd.extend(["--fit-from-date", fit_from_date.isoformat()])

    if fit_to_date is not None:
        cmd.extend(["--fit-to-date", fit_to_date.isoformat()])

    if forecast_start_rate_mode == "manual":
        if forecast_start_rate is None or forecast_start_rate <= 0:
            msg = (
                "Cuando forecast_start_rate_mode='manual', "
                "forecast_start_rate debe ser mayor que cero."
            )
            raise ValueError(msg)

        cmd.extend(["--forecast-start-rate", str(forecast_start_rate)])

    if history_csv is not None:
        cmd.extend(["--history-csv", str(history_csv)])

    if pvt_config_json is not None:
        cmd.extend(["--pvt-config-json", str(pvt_config_json)])

    return cmd


def run_command(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    """Run the workflow command from the project root."""
    return subprocess.run(
        cmd,
        cwd=PROJECT_ROOT,
        text=True,
        capture_output=True,
        check=False,
    )


def show_command(cmd: list[str]) -> None:
    """Render command in a readable shell-like form."""
    st.code(" ".join(cmd), language="bash")


def render_download_button(path: Path, label: str, mime: str) -> None:
    """Render a download button if the file exists."""
    if not path.exists():
        st.caption(f"No disponible todavía: `{path.name}`")
        return

    st.download_button(
        label=label,
        data=path.read_bytes(),
        file_name=path.name,
        mime=mime,
        use_container_width=True,
    )


def render_dataframe_from_csv(path: Path, title: str) -> None:
    """Render a CSV artifact as a dataframe."""
    st.subheader(title)

    df = read_csv_safe(path)
    if df is None:
        st.info(f"No se encontró `{path.name}`.")
        return

    st.dataframe(df, use_container_width=True, hide_index=True)


def render_json_report(path: Path, title: str) -> None:
    """Render a JSON artifact."""
    st.subheader(title)

    if not path.exists():
        st.info(f"No se encontró `{path.name}`.")
        return

    try:
        data = read_json(path)
    except Exception as exc:  # noqa: BLE001
        st.error(f"No fue posible leer `{path.name}`: {exc}")
        return

    st.json(data, expanded=True)


def render_png(path: Path, title: str) -> None:
    """Render a PNG artifact."""
    st.subheader(title)

    if not path.exists():
        st.info(f"No se encontró `{path.name}`.")
        return

    st.image(str(path), use_container_width=True)


def render_time_series(
    df: pd.DataFrame,
    *,
    title: str,
    columns: tuple[str, ...],
    y_label: str,
) -> None:
    """Render a Streamlit time-series chart for selected existing columns."""
    st.subheader(title)

    if "date" not in df.columns:
        st.info("No existe columna `date` para graficar serie de tiempo.")
        return

    selected_columns = existing_columns(df, columns)
    if not selected_columns:
        st.info(f"No hay columnas disponibles para graficar: {list(columns)}")
        return

    chart_df = df[["date", *selected_columns]].dropna(subset=["date"])
    if chart_df.empty:
        st.info("No hay datos válidos para graficar.")
        return

    chart_df = chart_df.set_index("date")
    st.line_chart(chart_df, y=selected_columns, height=360)
    st.caption(y_label)


def parse_plotly_selected_dates(points: list[dict[str, Any]]) -> tuple[date, date] | None:
    """Extract min/max dates from selected Plotly points."""
    raw_x_values = [point.get("x") for point in points if point.get("x") is not None]
    if not raw_x_values:
        return None

    parsed_dates = pd.to_datetime(raw_x_values, errors="coerce")
    parsed_dates = parsed_dates[~pd.isna(parsed_dates)]

    if len(parsed_dates) == 0:
        return None

    start_date = parsed_dates.min().date()
    end_date = parsed_dates.max().date()

    if start_date > end_date:
        start_date, end_date = end_date, start_date

    return start_date, end_date


def update_fit_window_from_selection(start_date: date, end_date: date) -> None:
    """Store selected fit window and rerun before updating sidebar widgets."""
    current_start = st.session_state.get(SESSION_FIT_FROM_DATE)
    current_end = st.session_state.get(SESSION_FIT_TO_DATE)

    if current_start == start_date and current_end == end_date:
        return

    st.session_state[SESSION_PENDING_FIT_WINDOW] = {
        "start_date": start_date.isoformat(),
        "end_date": end_date.isoformat(),
    }

    st.rerun()


def render_interactive_dca_fit_window_selector(enriched_df: pd.DataFrame) -> None:
    """Render interactive DCA fit-window selector using Plotly selection events."""
    st.subheader("Selección interactiva de ventana de ajuste DCA")

    if go is None:
        st.warning(
            "Plotly no está instalado. Agrega `plotly>=5.22` a requirements.txt "
            "y ejecuta `pip install plotly`."
        )
        return

    required_columns = {"date", "qo_stb_d"}
    missing_columns = required_columns.difference(enriched_df.columns)
    if missing_columns:
        st.info(
            "No es posible construir el selector interactivo. "
            f"Faltan columnas: {sorted(missing_columns)}"
        )
        return

    plot_df = enriched_df[["date", "qo_stb_d"]].copy()
    plot_df["date"] = pd.to_datetime(plot_df["date"], errors="coerce")
    plot_df["qo_stb_d"] = pd.to_numeric(plot_df["qo_stb_d"], errors="coerce")
    plot_df = plot_df.dropna(subset=["date", "qo_stb_d"]).sort_values("date")

    if plot_df.empty:
        st.info("No hay datos válidos de qo_stb_d para seleccionar ventana DCA.")
        return

    fit_from = st.session_state.get(SESSION_FIT_FROM_DATE)
    fit_to = st.session_state.get(SESSION_FIT_TO_DATE)

    fig = go.Figure()

    fig.add_trace(
        go.Scatter(
            x=plot_df["date"],
            y=plot_df["qo_stb_d"],
            mode="markers+lines",
            name="qo_stb_d",
            marker={"size": 7},
            customdata=plot_df["date"].dt.strftime("%Y-%m-%d"),
            hovertemplate=(
                "Fecha: %{customdata}<br>"
                "qo: %{y:,.2f} STB/d"
                "<extra></extra>"
            ),
        )
    )

    if isinstance(fit_from, date) and isinstance(fit_to, date):
        fig.add_vrect(
            x0=fit_from.isoformat(),
            x1=fit_to.isoformat(),
            fillcolor="LightSkyBlue",
            opacity=0.22,
            layer="below",
            line_width=0,
            annotation_text="Ventana actual",
            annotation_position="top left",
        )

    fig.update_layout(
        title="Arrastra una caja sobre los puntos que quieres usar para el ajuste",
        xaxis_title="Fecha",
        yaxis_title="Tasa de aceite, qo [STB/d]",
        dragmode="select",
        height=520,
        margin={"l": 20, "r": 20, "t": 60, "b": 20},
        legend={"orientation": "h"},
    )

    event = st.plotly_chart(
        fig,
        use_container_width=True,
        on_select="rerun",
        selection_mode=("box", "lasso"),
        key="dca_fit_window_selector",
        config={
            "displaylogo": False,
            "modeBarButtonsToAdd": ["select2d", "lasso2d"],
        },
    )

    st.caption(
        "Uso: selecciona puntos con click-and-drag. "
        "La app tomará la fecha mínima y máxima seleccionada como "
        "`fit_from_date` y `fit_to_date`."
    )

    selection = event.get("selection", {}) if isinstance(event, dict) else {}
    points = selection.get("points", []) if isinstance(selection, dict) else []

    if not points:
        st.info(
            "No hay selección activa. Puedes seguir usando las fechas manuales "
            "en la barra lateral."
        )
        return

    selected_window = parse_plotly_selected_dates(points)
    if selected_window is None:
        st.warning("No fue posible interpretar fechas en la selección.")
        return

    start_date, end_date = selected_window

    st.success(
        "Ventana seleccionada: "
        f"{start_date.isoformat()} → {end_date.isoformat()}. "
        "Actualizando controles laterales..."
    )
    update_fit_window_from_selection(start_date, end_date)


def render_m1_summary(enriched_df: pd.DataFrame) -> None:
    """Render M1 well/history visualization."""
    st.header("Módulo 1 | Pozo e historia de producción")

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric("Registros", f"{len(enriched_df):,}")

    with col2:
        if "date" in enriched_df.columns and enriched_df["date"].notna().any():
            st.metric(
                "Fecha inicial",
                enriched_df["date"].min().date().isoformat(),
            )
        else:
            st.metric("Fecha inicial", "N/D")

    with col3:
        if "date" in enriched_df.columns and enriched_df["date"].notna().any():
            st.metric(
                "Fecha final",
                enriched_df["date"].max().date().isoformat(),
            )
        else:
            st.metric("Fecha final", "N/D")

    with col4:
        if "pwf_source" in enriched_df.columns:
            measured_count = int((enriched_df["pwf_source"] == "measured").sum())
            estimated_count = int((enriched_df["pwf_source"] == "estimated").sum())
            st.metric("Pwf medida / estimada", f"{measured_count} / {estimated_count}")
        else:
            st.metric("Pwf medida / estimada", "N/D")

    render_time_series(
        enriched_df,
        title="Caudales de producción",
        columns=M1_RATE_COLUMNS,
        y_label="Aceite/agua en STB/d. Gas en MSCF/d si la columna existe.",
    )

    render_time_series(
        enriched_df,
        title="Presiones de cabeza y fondo",
        columns=M1_PRESSURE_COLUMNS,
        y_label="Presiones en psia.",
    )

    if "pwf_source" in enriched_df.columns:
        st.subheader("Distribución de fuente Pwf")
        source_counts = (
            enriched_df["pwf_source"]
            .fillna("unknown")
            .astype(str)
            .value_counts()
            .rename_axis("pwf_source")
            .reset_index(name="count")
        )
        st.dataframe(source_counts, use_container_width=True, hide_index=True)

    st.subheader("Tabla M1-M2 enriquecida")
    priority_columns = [
        column
        for column in (
            "well_id",
            "date",
            "qo_stb_d",
            "qg_mscf_d",
            "qw_stb_d",
            "whp_psia",
            "t_wh_f",
            "pwf_measured_psia",
            "pwf_estimated_psia",
            "pwf_used_psia",
            "pwf_source",
        )
        if column in enriched_df.columns
    ]

    if priority_columns:
        st.dataframe(
            enriched_df[priority_columns],
            use_container_width=True,
            hide_index=True,
        )
    else:
        st.dataframe(enriched_df, use_container_width=True, hide_index=True)


def render_m2_summary(enriched_df: pd.DataFrame) -> None:
    """Render M2 PVT visualization."""
    st.header("Módulo 2 | Propiedades PVT por fecha")

    pvt_columns = existing_columns(enriched_df, M2_PVT_COLUMNS)

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        if "bo" in enriched_df.columns:
            st.metric("Bo promedio", f"{as_float(enriched_df['bo'].mean()):,.4f} rb/STB")
        else:
            st.metric("Bo promedio", "N/D")

    with col2:
        if "rs" in enriched_df.columns:
            st.metric("Rs promedio", f"{as_float(enriched_df['rs'].mean()):,.2f}")
        else:
            st.metric("Rs promedio", "N/D")

    with col3:
        if "mu_o_cp" in enriched_df.columns:
            st.metric(
                "μo promedio",
                f"{as_float(enriched_df['mu_o_cp'].mean()):,.3f} cP",
            )
        else:
            st.metric("μo promedio", "N/D")

    with col4:
        if "calibrated_flag" in enriched_df.columns:
            calibrated_count = int(enriched_df["calibrated_flag"].fillna(False).sum())
            st.metric("Filas calibradas", f"{calibrated_count:,}")
        else:
            st.metric("Filas calibradas", "N/D")

    render_time_series(
        enriched_df,
        title="Propiedades PVT calculadas",
        columns=M2_PVT_COLUMNS,
        y_label="Unidades según contrato de datos: Bo rb/STB, μo cP, densidad lb/ft³, Pb psia.",
    )

    meta_columns = [
        column
        for column in (
            "well_id",
            "date",
            "bo",
            "rs",
            "mu_o_cp",
            "rho_o_lbft3",
            "pb_psia",
            "pvt_model_version",
            "oil_corr",
            "calibrated_flag",
        )
        if column in enriched_df.columns
    ]

    st.subheader("Tabla PVT integrada")
    if meta_columns:
        st.dataframe(
            enriched_df[meta_columns],
            use_container_width=True,
            hide_index=True,
        )
    elif pvt_columns:
        st.dataframe(
            enriched_df[pvt_columns],
            use_container_width=True,
            hide_index=True,
        )
    else:
        st.info("No se encontraron columnas PVT en la historia enriquecida.")


def render_quick_dca_summary(artifacts: WorkflowArtifacts) -> None:
    """Render high-level DCA metrics from fit results and QC report."""
    fit_df = read_csv_safe(artifacts.dca_fit_results_csv)
    if fit_df is None or fit_df.empty:
        return

    required_columns = {
        "model",
        "eur_stb",
        "forecast_qi_stb_d",
        "forecast_start_rate_mode",
        "rmse_stb_d",
    }
    missing_columns = required_columns.difference(fit_df.columns)
    if missing_columns:
        st.warning(
            "No fue posible construir el resumen rápido DCA. "
            f"Faltan columnas en fit_results: {sorted(missing_columns)}"
        )
        return

    best_row = fit_df.sort_values("rmse_stb_d", ascending=True).iloc[0]

    models_with_similar_rmse_count = 0
    if artifacts.dca_qc_report_json.exists():
        try:
            qc = read_json(artifacts.dca_qc_report_json)
            models_with_similar_rmse = qc.get("models_with_similar_rmse", [])
            if isinstance(models_with_similar_rmse, list):
                models_with_similar_rmse_count = len(models_with_similar_rmse)
        except Exception:  # noqa: BLE001
            models_with_similar_rmse_count = 0

    st.subheader("Resumen rápido DCA")

    col1, col2, col3, col4, col5 = st.columns(5)

    with col1:
        st.metric("Modelo base", str(best_row["model"]))

    with col2:
        eur_mstb = as_float(best_row["eur_stb"]) / 1_000.0
        st.metric("EUR base", f"{eur_mstb:,.3f} MSTB")

    with col3:
        st.metric("Modo tasa inicial", str(best_row["forecast_start_rate_mode"]))

    with col4:
        st.metric(
            "Tasa inicial forecast",
            f"{as_float(best_row['forecast_qi_stb_d']):,.2f} STB/d",
        )

    with col5:
        st.metric("Modelos RMSE similar", str(models_with_similar_rmse_count))


def render_sidebar_inputs() -> dict[str, Any]:
    """Render sidebar controls and return normalized values."""
    st.sidebar.header("Entrada M1-M2-M3")

    history_upload = st.sidebar.file_uploader(
        "history_csv",
        type=["csv"],
        help="Historia de producción del pozo.",
    )
    pvt_config_upload = st.sidebar.file_uploader(
        "pvt_config_json",
        type=["json"],
        help="Configuración PVT del pozo o escenario.",
    )

    well_id = st.sidebar.text_input("well_id", value="W001").strip()

    st.sidebar.divider()
    st.sidebar.header("Ventana de ajuste DCA")

    use_fit_from = st.sidebar.checkbox(
        "Usar fit_from_date",
        key=SESSION_USE_FIT_FROM,
    )
    fit_from_date = (
        st.sidebar.date_input(
            "fit_from_date",
            key=SESSION_FIT_FROM_DATE,
        )
        if use_fit_from
        else None
    )

    use_fit_to = st.sidebar.checkbox(
        "Usar fit_to_date",
        key=SESSION_USE_FIT_TO,
    )
    fit_to_date = (
        st.sidebar.date_input(
            "fit_to_date",
            key=SESSION_FIT_TO_DATE,
        )
        if use_fit_to
        else None
    )

    exclude_first_n = st.sidebar.number_input(
        "exclude_first_n",
        min_value=0,
        max_value=10_000,
        value=0,
        step=1,
    )

    st.sidebar.divider()
    st.sidebar.header("Forecast")

    forecast_days = st.sidebar.number_input(
        "forecast_days",
        min_value=1,
        max_value=50_000,
        value=3650,
        step=30,
    )

    abandonment_rate = st.sidebar.number_input(
        "abandonment_rate",
        min_value=0.0,
        value=50.0,
        step=1.0,
        help="Tasa económica o técnica de abandono.",
    )

    forecast_start_rate_mode = st.sidebar.selectbox(
        "forecast_start_rate_mode",
        options=FORECAST_START_RATE_MODES,
        index=1,
    )

    forecast_start_rate = None
    if forecast_start_rate_mode == "manual":
        forecast_start_rate = st.sidebar.number_input(
            "forecast_start_rate",
            min_value=0.000001,
            value=100.0,
            step=1.0,
        )

    return {
        "history_upload": history_upload,
        "pvt_config_upload": pvt_config_upload,
        "well_id": well_id,
        "fit_from_date": fit_from_date,
        "fit_to_date": fit_to_date,
        "exclude_first_n": int(exclude_first_n),
        "forecast_days": int(forecast_days),
        "abandonment_rate": float(abandonment_rate),
        "forecast_start_rate_mode": forecast_start_rate_mode,
        "forecast_start_rate": (
            float(forecast_start_rate) if forecast_start_rate is not None else None
        ),
    }


def render_artifacts(well_id: str) -> None:
    """Render generated workflow artifacts."""
    artifacts = WorkflowArtifacts.for_well(well_id)
    enriched_df = read_csv_safe(artifacts.enriched_history_csv)

    render_quick_dca_summary(artifacts)

    tabs = st.tabs(
        [
            "M1 Pozo / Historia",
            "M2 PVT",
            "M3 DCA",
            "Selección ventana DCA",
            "Gráficas DCA",
            "Descargas",
        ]
    )

    with tabs[0]:
        if enriched_df is None:
            st.info(f"No se encontró `{artifacts.enriched_history_csv.name}`.")
        else:
            render_m1_summary(enriched_df)

    with tabs[1]:
        if enriched_df is None:
            st.info(f"No se encontró `{artifacts.enriched_history_csv.name}`.")
        else:
            render_m2_summary(enriched_df)

    with tabs[2]:
        render_dataframe_from_csv(
            artifacts.dca_fit_results_csv,
            "fit_results",
        )
        render_json_report(
            artifacts.dca_qc_report_json,
            "dca_qc_report",
        )

    with tabs[3]:
        if enriched_df is None:
            st.info(
                "Ejecuta primero el workflow para generar la historia enriquecida "
                "y habilitar la selección interactiva."
            )
        else:
            render_interactive_dca_fit_window_selector(enriched_df)

    with tabs[4]:
        col_fit, col_forecast = st.columns(2)
        with col_fit:
            render_png(
                artifacts.dca_rate_fit_png,
                "Ajuste de tasa",
            )
        with col_forecast:
            render_png(
                artifacts.dca_forecast_plot_png,
                "Forecast DCA",
            )

    with tabs[5]:
        st.subheader("Descargar artefactos")
        col_csv, col_json, col_png = st.columns(3)

        with col_csv:
            render_download_button(
                artifacts.enriched_history_csv,
                "Descargar historia enriquecida CSV",
                "text/csv",
            )
            render_download_button(
                artifacts.dca_fit_results_csv,
                "Descargar fit_results CSV",
                "text/csv",
            )

        with col_json:
            render_download_button(
                artifacts.dca_qc_report_json,
                "Descargar QC JSON",
                "application/json",
            )

        with col_png:
            render_download_button(
                artifacts.dca_rate_fit_png,
                "Descargar ajuste PNG",
                "image/png",
            )
            render_download_button(
                artifacts.dca_forecast_plot_png,
                "Descargar forecast PNG",
                "image/png",
            )


def main() -> None:
    """Run the Streamlit app."""
    configure_page()
    initialize_session_defaults()
    apply_light_css()
    ensure_dirs()

    st.title("ecoRTA | Workflow M1-M2-M3")
    st.caption(
        "Módulo 1: historia de pozo y Pwf. "
        "Módulo 2: propiedades PVT. "
        "Módulo 3: curvas de declinación Arps."
    )

    inputs = render_sidebar_inputs()

    if not inputs["well_id"]:
        st.warning("Define un well_id válido para ejecutar el workflow.")
        return

    st.info(
        "La interfaz ejecuta el pipeline existente y muestra los artefactos "
        "generados. No duplica lógica de integración, PVT ni DCA."
    )

    history_csv_path = save_uploaded_file(
        inputs["history_upload"],
        f"{inputs['well_id']}_history_upload.csv",
    )
    pvt_config_json_path = save_uploaded_file(
        inputs["pvt_config_upload"],
        f"{inputs['well_id']}_pvt_config_upload.json",
    )

    try:
        cmd = build_full_workflow_command(
            well_id=inputs["well_id"],
            fit_from_date=inputs["fit_from_date"],
            fit_to_date=inputs["fit_to_date"],
            exclude_first_n=inputs["exclude_first_n"],
            forecast_days=inputs["forecast_days"],
            abandonment_rate=inputs["abandonment_rate"],
            forecast_start_rate_mode=inputs["forecast_start_rate_mode"],
            forecast_start_rate=inputs["forecast_start_rate"],
            history_csv=history_csv_path,
            pvt_config_json=pvt_config_json_path,
        )
    except ValueError as exc:
        st.error(str(exc))
        return

    with st.expander("Comando equivalente", expanded=False):
        show_command(cmd)

    run_clicked = st.button(
        "Ejecutar workflow M1-M2-M3",
        type="primary",
        use_container_width=True,
    )

    if run_clicked:
        with st.spinner("Ejecutando workflow M1-M2-M3..."):
            result = run_command(cmd)

        if result.returncode != 0:
            st.error("El workflow terminó con error.")
            st.subheader("STDERR")
            st.code(result.stderr or "(vacío)", language="text")
            st.subheader("STDOUT")
            st.code(result.stdout or "(vacío)", language="text")
            return

        st.success("Workflow ejecutado correctamente.")

        if result.stdout:
            with st.expander("STDOUT", expanded=False):
                st.code(result.stdout, language="text")

        if result.stderr:
            with st.expander("STDERR", expanded=False):
                st.code(result.stderr, language="text")

    render_artifacts(inputs["well_id"])


if __name__ == "__main__":
    main()