"""Streamlit UI for ecoRTA workflows.

This UI is intentionally thin:
- It collects user inputs.
- It executes the existing CLI pipeline.
- It displays generated CSV/JSON/PNG artifacts.

No DCA, PVT, or well-integration logic is duplicated here.
"""

from __future__ import annotations

import json
import subprocess
import sys
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any

import pandas as pd
import streamlit as st


PROJECT_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_DIR = PROJECT_ROOT / "output"
UI_INPUT_DIR = PROJECT_ROOT / "data" / "ui_uploads"

FORECAST_START_RATE_MODES = (
    "fitted",
    "last-window-rate",
    "manual",
)


@dataclass(frozen=True)
class WorkflowArtifacts:
    """Expected output artifacts generated by the full workflow."""

    enriched_history_csv: Path
    dca_fit_results_csv: Path
    dca_qc_report_json: Path
    dca_rate_fit_png: Path
    dca_forecast_plot_png: Path

    @classmethod
    def for_well(cls, well_id: str) -> "WorkflowArtifacts":
        safe_well_id = well_id.strip()
        return cls(
            enriched_history_csv=OUTPUT_DIR / f"{safe_well_id}_history_enriched.csv",
            dca_fit_results_csv=OUTPUT_DIR / f"{safe_well_id}_dca_fit_results.csv",
            dca_qc_report_json=OUTPUT_DIR / f"{safe_well_id}_dca_qc_report.json",
            dca_rate_fit_png=OUTPUT_DIR / f"{safe_well_id}_dca_rate_fit.png",
            dca_forecast_plot_png=OUTPUT_DIR / f"{safe_well_id}_dca_forecast_plot.png",
        )


def configure_page() -> None:
    """Configure Streamlit page defaults."""
    st.set_page_config(
        page_title="ecoRTA | DCA",
        page_icon="📉",
        layout="wide",
    )


def ensure_dirs() -> None:
    """Create required runtime folders."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    UI_INPUT_DIR.mkdir(parents=True, exist_ok=True)


def save_uploaded_file(uploaded_file: Any, target_name: str) -> Path | None:
    """Persist an uploaded Streamlit file and return its path."""
    if uploaded_file is None:
        return None

    target_path = UI_INPUT_DIR / target_name
    target_path.write_bytes(uploaded_file.getbuffer())
    return target_path


def read_json(path: Path) -> dict[str, Any]:
    """Read a JSON file safely."""
    with path.open("r", encoding="utf-8") as file:
        data = json.load(file)

    if not isinstance(data, dict):
        msg = f"El archivo JSON no contiene un objeto raíz válido: {path}"
        raise ValueError(msg)

    return data


def build_full_workflow_command(
    *,
    well_id: str,
    fit_from_date: date | None,
    fit_to_date: date | None,
    exclude_first_n: int,
    forecast_days: int,
    abandonment_rate: float,
    forecast_start_rate_mode: str,
    forecast_start_rate: float | None,
    history_csv: Path | None,
    pvt_config_json: Path | None,
) -> list[str]:
    """Build the existing CLI command for the full M1-M2-M3 workflow."""
    cmd = [
        sys.executable,
        "-m",
        "src.pipeline.run_full_workflow",
        "--well-id",
        well_id,
        "--exclude-first-n",
        str(exclude_first_n),
        "--forecast-days",
        str(forecast_days),
        "--abandonment-rate",
        str(abandonment_rate),
        "--forecast-start-rate-mode",
        forecast_start_rate_mode,
    ]

    if fit_from_date is not None:
        cmd.extend(["--fit-from-date", fit_from_date.isoformat()])

    if fit_to_date is not None:
        cmd.extend(["--fit-to-date", fit_to_date.isoformat()])

    if forecast_start_rate_mode == "manual":
        if forecast_start_rate is None or forecast_start_rate <= 0:
            msg = (
                "Cuando forecast_start_rate_mode='manual', "
                "forecast_start_rate debe ser mayor que cero."
            )
            raise ValueError(msg)
        cmd.extend(["--forecast-start-rate", str(forecast_start_rate)])

    # These flags assume run_full_workflow.py already supports uploaded input paths.
    # If your current CLI uses different names, only adjust these two flag names.
    if history_csv is not None:
        cmd.extend(["--history-csv", str(history_csv)])

    if pvt_config_json is not None:
        cmd.extend(["--pvt-config-json", str(pvt_config_json)])

    return cmd


def run_command(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    """Run the workflow command from project root."""
    return subprocess.run(
        cmd,
        cwd=PROJECT_ROOT,
        text=True,
        capture_output=True,
        check=False,
    )


def show_command(cmd: list[str]) -> None:
    """Render command in a readable form."""
    st.code(" ".join(cmd), language="bash")


def render_download_button(path: Path, label: str, mime: str) -> None:
    """Render a download button if a file exists."""
    if not path.exists():
        st.caption(f"No disponible todavía: `{path.name}`")
        return

    st.download_button(
        label=label,
        data=path.read_bytes(),
        file_name=path.name,
        mime=mime,
        use_container_width=True,
    )


def render_dataframe_from_csv(path: Path, title: str) -> None:
    """Render a CSV artifact as a dataframe."""
    st.subheader(title)

    if not path.exists():
        st.info(f"No se encontró `{path.name}`.")
        return

    try:
        df = pd.read_csv(path)
    except Exception as exc:  # noqa: BLE001
        st.error(f"No fue posible leer `{path.name}`: {exc}")
        return

    st.dataframe(df, use_container_width=True, hide_index=True)


def render_json_report(path: Path, title: str) -> None:
    """Render a JSON artifact."""
    st.subheader(title)

    if not path.exists():
        st.info(f"No se encontró `{path.name}`.")
        return

    try:
        data = read_json(path)
    except Exception as exc:  # noqa: BLE001
        st.error(f"No fue posible leer `{path.name}`: {exc}")
        return

    st.json(data, expanded=True)


def render_png(path: Path, title: str) -> None:
    """Render a PNG artifact."""
    st.subheader(title)

    if not path.exists():
        st.info(f"No se encontró `{path.name}`.")
        return

    st.image(str(path), use_container_width=True)


def render_sidebar_inputs() -> dict[str, Any]:
    """Render sidebar controls and return normalized values."""
    st.sidebar.header("Entrada M1-M2-M3")

    history_upload = st.sidebar.file_uploader(
        "history_csv",
        type=["csv"],
        help="Historia de producción del pozo.",
    )
    pvt_config_upload = st.sidebar.file_uploader(
        "pvt_config_json",
        type=["json"],
        help="Configuración PVT del pozo o escenario.",
    )

    well_id = st.sidebar.text_input("well_id", value="W001").strip()

    st.sidebar.divider()
    st.sidebar.header("Ventana de ajuste DCA")

    use_fit_from = st.sidebar.checkbox("Usar fit_from_date", value=True)
    fit_from_date = (
        st.sidebar.date_input("fit_from_date", value=date(2024, 7, 1))
        if use_fit_from
        else None
    )

    use_fit_to = st.sidebar.checkbox("Usar fit_to_date", value=True)
    fit_to_date = (
        st.sidebar.date_input("fit_to_date", value=date(2025, 11, 30))
        if use_fit_to
        else None
    )

    exclude_first_n = st.sidebar.number_input(
        "exclude_first_n",
        min_value=0,
        max_value=10_000,
        value=0,
        step=1,
    )

    st.sidebar.divider()
    st.sidebar.header("Forecast")

    forecast_days = st.sidebar.number_input(
        "forecast_days",
        min_value=1,
        max_value=50_000,
        value=3650,
        step=30,
    )

    abandonment_rate = st.sidebar.number_input(
        "abandonment_rate",
        min_value=0.0,
        value=50.0,
        step=1.0,
        help="Tasa económica o técnica de abandono.",
    )

    forecast_start_rate_mode = st.sidebar.selectbox(
        "forecast_start_rate_mode",
        options=FORECAST_START_RATE_MODES,
        index=1,
    )

    forecast_start_rate = None
    if forecast_start_rate_mode == "manual":
        forecast_start_rate = st.sidebar.number_input(
            "forecast_start_rate",
            min_value=0.000001,
            value=100.0,
            step=1.0,
        )

    return {
        "history_upload": history_upload,
        "pvt_config_upload": pvt_config_upload,
        "well_id": well_id,
        "fit_from_date": fit_from_date,
        "fit_to_date": fit_to_date,
        "exclude_first_n": int(exclude_first_n),
        "forecast_days": int(forecast_days),
        "abandonment_rate": float(abandonment_rate),
        "forecast_start_rate_mode": forecast_start_rate_mode,
        "forecast_start_rate": (
            float(forecast_start_rate) if forecast_start_rate is not None else None
        ),
    }


def render_artifacts(well_id: str) -> None:
    """Render generated workflow artifacts."""
    artifacts = WorkflowArtifacts.for_well(well_id)

    tabs = st.tabs(
        [
            "Resumen DCA",
            "Historia enriquecida",
            "Gráficas",
            "Descargas",
        ]
    )

    with tabs[0]:
        render_dataframe_from_csv(
            artifacts.dca_fit_results_csv,
            "fit_results",
        )
        render_json_report(
            artifacts.dca_qc_report_json,
            "dca_qc_report",
        )

    with tabs[1]:
        render_dataframe_from_csv(
            artifacts.enriched_history_csv,
            "history_enriched",
        )

    with tabs[2]:
        col_fit, col_forecast = st.columns(2)
        with col_fit:
            render_png(
                artifacts.dca_rate_fit_png,
                "Ajuste de tasa",
            )
        with col_forecast:
            render_png(
                artifacts.dca_forecast_plot_png,
                "Forecast DCA",
            )

    with tabs[3]:
        st.subheader("Descargar artefactos")
        col_csv, col_json, col_png = st.columns(3)

        with col_csv:
            render_download_button(
                artifacts.enriched_history_csv,
                "Descargar historia enriquecida CSV",
                "text/csv",
            )
            render_download_button(
                artifacts.dca_fit_results_csv,
                "Descargar fit_results CSV",
                "text/csv",
            )

        with col_json:
            render_download_button(
                artifacts.dca_qc_report_json,
                "Descargar QC JSON",
                "application/json",
            )

        with col_png:
            render_download_button(
                artifacts.dca_rate_fit_png,
                "Descargar ajuste PNG",
                "image/png",
            )
            render_download_button(
                artifacts.dca_forecast_plot_png,
                "Descargar forecast PNG",
                "image/png",
            )


def main() -> None:
    """Run the Streamlit app."""
    configure_page()
    ensure_dirs()

    st.title("ecoRTA | Interfaz DCA")
    st.caption(
        "Workflow integrado M1-M2-M3: historia de pozo, PVT y declinación Arps."
    )

    inputs = render_sidebar_inputs()

    if not inputs["well_id"]:
        st.warning("Define un well_id válido para ejecutar el workflow.")
        return

    st.info(
        "La UI ejecuta el pipeline existente y muestra los artefactos generados. "
        "No duplica lógica de integración, PVT ni DCA."
    )

    history_csv_path = save_uploaded_file(
        inputs["history_upload"],
        f"{inputs['well_id']}_history_upload.csv",
    )
    pvt_config_json_path = save_uploaded_file(
        inputs["pvt_config_upload"],
        f"{inputs['well_id']}_pvt_config_upload.json",
    )

    try:
        cmd = build_full_workflow_command(
            well_id=inputs["well_id"],
            fit_from_date=inputs["fit_from_date"],
            fit_to_date=inputs["fit_to_date"],
            exclude_first_n=inputs["exclude_first_n"],
            forecast_days=inputs["forecast_days"],
            abandonment_rate=inputs["abandonment_rate"],
            forecast_start_rate_mode=inputs["forecast_start_rate_mode"],
            forecast_start_rate=inputs["forecast_start_rate"],
            history_csv=history_csv_path,
            pvt_config_json=pvt_config_json_path,
        )
    except ValueError as exc:
        st.error(str(exc))
        return

    with st.expander("Comando equivalente", expanded=False):
        show_command(cmd)

    run_clicked = st.button(
        "Ejecutar workflow M1-M2-M3",
        type="primary",
        use_container_width=True,
    )

    if run_clicked:
        with st.spinner("Ejecutando workflow..."):
            result = run_command(cmd)

        if result.returncode != 0:
            st.error("El workflow terminó con error.")
            st.subheader("STDERR")
            st.code(result.stderr or "(vacío)", language="text")
            st.subheader("STDOUT")
            st.code(result.stdout or "(vacío)", language="text")
            return

        st.success("Workflow ejecutado correctamente.")

        if result.stdout:
            with st.expander("STDOUT", expanded=False):
                st.code(result.stdout, language="text")

        if result.stderr:
            with st.expander("STDERR", expanded=False):
                st.code(result.stderr, language="text")

    render_artifacts(inputs["well_id"])


if __name__ == "__main__":
    main()