"""Internal demo type-curve data for early M4 integration.

These values are placeholders for software plumbing only.
They must not be used as validated engineering type curves.
The project should replace them with digitized/validated tables from
approved technical references.
"""

from __future__ import annotations

DEMO_TYPE_CURVE_ROWS: list[dict[str, object]] = [
    {
        "method": "fetkovich",
        "curve_id": "fetkovich_demo_b_0_0",
        "curve_family": "arps_decline_demo",
        "x": 0.01,
        "y": 0.99,
        "x_label": "tDd",
        "y_label": "qDd",
        "source": "internal_demo",
        "status": "demo",
        "notes": "Placeholder only. Replace with validated Fetkovich table/digitized curve.",
    },
    {
        "method": "fetkovich",
        "curve_id": "fetkovich_demo_b_0_0",
        "curve_family": "arps_decline_demo",
        "x": 0.1,
        "y": 0.91,
        "x_label": "tDd",
        "y_label": "qDd",
        "source": "internal_demo",
        "status": "demo",
        "notes": "Placeholder only. Replace with validated Fetkovich table/digitized curve.",
    },
    {
        "method": "fetkovich",
        "curve_id": "fetkovich_demo_b_0_0",
        "curve_family": "arps_decline_demo",
        "x": 1.0,
        "y": 0.5,
        "x_label": "tDd",
        "y_label": "qDd",
        "source": "internal_demo",
        "status": "demo",
        "notes": "Placeholder only. Replace with validated Fetkovich table/digitized curve.",
    },
    {
        "method": "palacio_blasingame",
        "curve_id": "palacio_blastingame_demo_liquid",
        "curve_family": "normalized_rate_integral_demo",
        "x": 0.01,
        "y": 1.0,
        "x_label": "tDa",
        "y_label": "qDd",
        "source": "internal_demo",
        "status": "demo",
        "notes": "Placeholder only. Replace with validated Palacio-Blasingame table/digitized curve.",
    },
    {
        "method": "palacio_blasingame",
        "curve_id": "palacio_blastingame_demo_liquid",
        "curve_family": "normalized_rate_integral_demo",
        "x": 0.1,
        "y": 0.82,
        "x_label": "tDa",
        "y_label": "qDd",
        "source": "internal_demo",
        "status": "demo",
        "notes": "Placeholder only. Replace with validated Palacio-Blasingame table/digitized curve.",
    },
    {
        "method": "palacio_blasingame",
        "curve_id": "palacio_blastingame_demo_liquid",
        "curve_family": "normalized_rate_integral_demo",
        "x": 1.0,
        "y": 0.42,
        "x_label": "tDa",
        "y_label": "qDd",
        "source": "internal_demo",
        "status": "demo",
        "notes": "Placeholder only. Replace with validated Palacio-Blasingame table/digitized curve.",
    },
    {
        "method": "agarwal_gardner",
        "curve_id": "agarwal_gardner_demo_radial",
        "curve_family": "combined_decline_type_curve_demo",
        "x": 0.01,
        "y": 0.97,
        "x_label": "tD",
        "y_label": "qD",
        "source": "internal_demo",
        "status": "demo",
        "notes": "Placeholder only. Replace with validated Agarwal-Gardner table/digitized curve.",
    },
    {
        "method": "agarwal_gardner",
        "curve_id": "agarwal_gardner_demo_radial",
        "curve_family": "combined_decline_type_curve_demo",
        "x": 0.1,
        "y": 0.76,
        "x_label": "tD",
        "y_label": "qD",
        "source": "internal_demo",
        "status": "demo",
        "notes": "Placeholder only. Replace with validated Agarwal-Gardner table/digitized curve.",
    },
    {
        "method": "agarwal_gardner",
        "curve_id": "agarwal_gardner_demo_radial",
        "curve_family": "combined_decline_type_curve_demo",
        "x": 1.0,
        "y": 0.33,
        "x_label": "tD",
        "y_label": "qD",
        "source": "internal_demo",
        "status": "demo",
        "notes": "Placeholder only. Replace with validated Agarwal-Gardner table/digitized curve.",
    },
]